version: 1
disable_existing_loggers: False
formatters:
  simple:
      format: "%(asctime)s - [%(name)s] - [%(levelname)s] :%(levelno)s: %(message)s"
      datefmt: '%F %T'
handlers:
  console:
      class: logging.StreamHandler
      formatter: simple
      level: INFO
      stream: ext://sys.stdout
  file_handler:
      class: logging.FileHandler
      formatter: simple
      level: INFO
      filename: ./logs/demo_run.log
loggers:
  root:
    level: DEBUG
    handlers: [console, file_handler]
